server:
  port: 9000
  hostname: localhost

spring:
  application:
    name: spring-cloud-api-gateway
  main:
    web-application-type: reactive
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: true
    registerWithEureka: true
  instance:
    hostname: localhost




